apiVersion: apps/v1
kind: Deployment
metadata: #4 changes
  name: nutritionschedule-mongo-depl
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: nutritionschedule-mongo
  template: 
    metadata:
      labels: 
        app: nutritionschedule-mongo
    spec: 
      containers:
        - name: nutritionschedule-mongo
          image: mongo
---
apiVersion: v1
kind: Service #3 changes
metadata:
  name: nutritionschedule-mongo-srv
spec:
  selector:
    app: nutritionschedule-mongo
  ports: 
    - name: nutritionschedule-db
      protocol: TCP
      port: 27016 
      targetPort: 27017
      