apiVersion: v1
kind: Service
metadata:
  name: api-gateway-nodeport-srv
spec:
  type: NodePort
  selector:
    app: api-gateway-nodeport
  ports:
    - name: api-gateway-nodeport
      protocol: TCP
      nodePort: 30777
      port: 3000
      targetPort: 3000


