apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userdb-mongo-srv #how deployment find pod
  template:
    metadata:
      labels:
        app: userdb-mongo-srv #pod name
        selector: userdb-mongo-depl
    spec:
      containers:
        - name: userdb-mongo-depl
          image: mongo
          ports:
            - containerPort: 27017
              name: userdb-mongo
---
apiVersion: v1
kind: Service
metadata:
  name: userdb-mongo-srv #domain name
spec:
  selector:
    app: userdb-mongo-srv #find from deployment
  ports:
    - name: userdb-mongo-srv
      protocol: TCP
      port: 27017
      targetPort: 27017
